import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import WeatherPage from "~/pages/components/Weather";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const UserIsSignedIn = () => {
  const user = useUser();
  return (
    <div className="flex justify-end">
      <div className="m-1 pr-4">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden whitespace-normal break-all">
        <UserIsSignedIn />
        <WeatherPage />
      </main>
    </>
  );
};

export default Home;
